### PR TITLE
Modular Melee Attack and Melee Attack Input Modification

### PR DESCRIPTION
**Pull request by NoShenGG**
## Description
I removed the activation of OnMelee in the PlayerController MonoBehavior when releasing the key to avoid double activation when pressing the input. In addition to this, I added the ability to buffer attacks by inputting a melee attack in between melee attacks. There was also a chain attack implementation that allows for a customizable window of time to allow chaining attacks into the next hitbox.

## Related Task
https://app.clickup.com/t/8678rg8te

## Testing
I tested to see if the chain attack window would keep the chain of hitboxes going even if you didn't immediately attack after but were still in the window of time. I also tested to see if the chain of hitboxes will reset after the chain attack window. The buffer implementation was tested by inputting two inputs in quick succession to see if it would still attack after the initial attack. I don't believe these changes to the melee attacks should impact other areas of the code.

### CODE REVIEW

**Comment by esl1350** [comment]
looks good! the buffering seems like it works well tyty

before i merge do you think you could make these changes to the player prefab as well?

**Comment by NoShenGG** [comment]
Should have updated it! Let me know if there's anything else.

**Comment by esl1350** [comment]
image
I'm getting this error trying to play the template scene - triggered whenever the melee hitbox hits an enemy - is there something that's not configured correctly in that scene?

**Comment by esl1350** [comment]
wait just kidding player prefab didn't have attack stat 💀 retarget to sprint-2 and you should be good to take on another task if you'd like!

**Comment by NoShenGG** [comment]
Retargeted :)

**Pull request merged**
