### PR TITLE
Ranged Enemy AI

### PR DESCRIPTION
**Pull request by IanCVal94**
## Description
Added in Prefab for a new enemy type that will be able to shoot at the player on a timer once a certain distance from them. The prefab includes new scripts for this new enemy variant for the movement logic and the enemy projectile logic to aim at the player and take damage if the projectile hits the player.

## Related Task
(https://sharing.clickup.com/9010021133/t/h/8678rg3uw/KY7QZHFG616DVBW)

## Testing
- The testing environment mainly consisted of a normal enemy and the ranged enemy to show the difference with each one of them and specifically test the projectile moving from the enemy to the player and the distance at which the enemy stops from the player. Also specifically tested if the projectile would disappear and take damage when interacting with the player. Also tested some safety features like the timer for the projectile so it would disappear after a certain amount of time so there aren't too many projectiles that fill up the game environment.
- Mainly made changes to some of the existing prefabs to assist some of the changes with this new enemy AI and since there was a GitHub issue that had the text font files deleted, I had to reassign all the prefabs with the correct font for the enemy health to appear again.

## Screenshots (if appropriate):
image

### CODE REVIEW

**Comment by ChaseOB** [comment]
Retarget to sprint-1

**Comment by IanCVal94** [comment]
Finished with final touches so far with the ranged AI

**Comment by IanCVal94** [comment]
Retargeted to Sprint 2

**Comment by esl1350** [comment]
looks good!!! thank you

**Pull request merged**
